FROM python:3.9.6
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip3 install setuptools twine 
COPY . .
# RUN ["python3", "setup.py"]
RUN python3 setup.py sdist bdist_wheel 
CMD [ "twine", "upload", "--verbose" ,"dist/*" ]